base_url = "https://verenagd.github.io/Fast-Robots/"
title = "Fast Robots"
description = "Fast Robots blog"

theme = "duckquill"

compile_sass = true
minify_html = true
generate_feeds = false
#feed_filenames = ["rss.xml", "atom.xml"]

[extra]
default_theme = "light"
accent_color = "#b48cff"        # light purple
accent_color_dark = "#9d7ae8"
emoji_favicon = "ðŸš€âœ¨"

[extra.nav]
show_feed = false
show_theme_switcher = true
show_repo = false
links = [
  { name = "Labs", menu = [
  { url = "@/Lab_1.md", name = "Lab 1" },
  { url = "@/Lab_2.md", name = "Lab 2" }
  ] },
  { url = "@/about.md", name = "About" },

]







